source("dataLoader.R")
agg <- aggregate(NEI$Emissions,by=list(NEI$year),FUN=sum)
png(file = "plots/plot1.png")
barplot(agg$x,names.arg=agg$Group.1,main='US PM25 Emissions',ylab='Tons',xlab='Year')
dev.off()